# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Country.create(name: "Greece", description: " is a country located in Southeast Europe. Its population is approximately 10.7 million as of 2018; Athens is its largest and capital city, followed by Thessaloniki. Situated on the southern tip of the Balkans, Greece is located at the crossroads of Europe, Asia, and Africa.Greece is a unitary parliamentary republic, and a developed country, with an advanced high-income economy, and a high quality of life, ranking simultaneously very high in the Human Development Index.",
     culture: "The culture of Greece has evolved over thousands of years, beginning in Mycenaean Greece and continuing most notably into Classical Greece, through the influence of the Roman Empire and its Greek Eastern continuation, the Eastern Roman or Byzantine Empire.",
      climate: "The climate of Greece is primarily Mediterranean,[150] featuring mild, wet winters and hot, dry summers." )
Country.create(name: "Spain", description: "officially the Kingdom of Spain[11] (Spanish: Reino de España),[a][b] is a country in Southwestern Europe with some pockets of territory across the Strait of Gibraltar and the Atlantic Ocean.[11] Its continental European territory is situated on the Iberian Peninsula.With an area of 505,990 km2 (195,360 sq mi), Spain is the largest country in Southern Europe, the second-largest country in Western Europe and the European Union, and the fourth-largest country by area on the European continent.Modern humans first arrived in the Iberian Peninsula around 35,000 years ago.",
     culture: "Spain is a Western country. Almost every aspect of Spanish life is permeated by its Roman heritage, making Spain one of the major Latin countries of Europe. Spanish culture is marked by strong historic ties to Catholicism, which played a pivotal role in the country's formation and subsequent identity.",
      climate: "Three main climatic zones can be separated, according to geographical situation and orographic conditions:The Mediterranean climate, characterised by warm/hot and dry summers, is dominant in the peninsula. The Mediterranean climate, characterised by warm/hot and dry summers, is dominant in the peninsula. where true hot desert summers exist. And The oceanic climate (Cfb), located in the northern quarter of the country, especially in the Atlantic region. where a humid subtropical variant occures. " )
Country.create(name: "Morocco", description: "Kingdom of Morocco, The capital is Rabat and the largest city is Casablanca.[15] Morocco spans an area of 710,850 km2 (274,460 sq mi) and has a population of over 37 million. is a country located in the Maghreb region of North Africa. It overlooks the Mediterranean Sea to the north and the Atlantic Ocean to the west, with land borders with Algeria to the east and Western Sahara (status disputed) to the south.",
     culture: "Each region possesses its own specificities, thus contributing to the national culture and to the legacy of civilization. Morocco has set among its top priorities the protection of its diverse legacy and the preservation of its cultural heritage. Culturally speaking, Morocco has always been successful in combining its Berber, Jewish and Arabic cultural heritage with external influences such as the French and the Spanish and, during the last decades, the Anglo-American lifestyles.",
      climate: "The country's Mediterranean climate is similar to that of southern California, with lush forests in the northern and central mountain ranges of the country, giving way to drier conditions and inland deserts further southeast. The Moroccan coastal plains experience remarkably moderate temperatures even in summer, owing to the effect of the cold Canary Current off its Atlantic coast." )
Country.create(name: "Italy", description: "Italy has a territorial enclave in Switzerland (Campione) and a maritime exclave in Tunisian waters (Lampedusa). With around 60 million inhabitants, Italy is the third-most populous member state of the European Union.is a country consisting of a peninsula delimited by the Alps and several islands surrounding it. Italy is located in South-Central Europe, and is considered part of Western Europe.",
    culture: "Divided by politics and geography for centuries until its eventual unification in 1861, Italy's culture has been shaped by a multitude of regional customs and local centres of power and patronage. Italy has had a central role in Western culture for centuries and is still recognised for its cultural traditions and artists.",
     climate: "Because of the great longitudinal extension of the peninsula and the mostly mountainous internal conformation, the climate of Italy is highly diverse." )
Country.create(name: "Ireland", description: "Geopolitically, Ireland is divided between the Republic of Ireland (officially named Ireland), which covers five-sixths of the island, and Northern Ireland, which is part of the United Kingdom. In 2011, the population of Ireland was about 6.6 million, ranking it the second-most populous island in Europe after Great Britain. As of 2016, 4.8 million live in the Republic of Ireland, and 1.8 million live in Northern Ireland. Ireland is the second-largest island of the British Isles, the third-largest in Europe, and the twentieth-largest on Earth.",
    culture: "Ireland's culture comprises elements of the culture of ancient peoples, later immigrant and broadcast cultural influences. In broad terms, Ireland is regarded as one of the Celtic nations of Europe, alongside Scotland, Wales, Cornwall, Isle of Man and Brittany. This combination of cultural influences is visible. ",
     climate: "The island's lush vegetation, a product of its mild climate and frequent rainfall, earns it the sobriquet the Emerald Isle. Overall, Ireland has a mild but changeable oceanic climate with few extremes. The climate is typically insular and is temperate, avoiding the extremes in temperature of many other areas in the world at similar latitudes." )
Country.create(name: "Colombia", description: "officially the Republic of Colombia,  It comprises 32 departments and the Capital District of Bogotá, the country's largest city.With over 50 million inhabitants Colombia is one of the most ethnically and linguistically diverse countries in the world, with its rich cultural heritage reflecting influences by various Amerindian civilizations, European settlement, forced African labor, and immigration from Europe and the greater Middle East.",
    culture: "Colombia lies at the crossroads of Latin America and the broader American continent, and as such has been hit by a wide range of cultural influences. Native American, Spanish and other European, African, American, Caribbean, and Middle Eastern influences, as well as other Latin American cultural influences, are all present in Colombia's modern culture. Urban migration, industrialization, globalization, and other political, social and economic changes have also left an impression. Many national symbols, both objects and themes, have arisen from Colombia's diverse cultural traditions and aim to represent what Colombia, and the Colombian people, have in common. Cultural expressions in Colombia are promoted by the government through the Ministry of Culture.",
     climate: "The climate of Colombia is characterized for being tropical presenting variations within six natural regions and depending on the altitude, temperature, humidity, winds and rainfall.[152] The diversity of climate zones in Colombia is characterized for having tropical rainforests, savannas, steppes, deserts and mountain climate." )
Country.create(name: "Brazil", description: "officially the Federative Republic of Brazil, the largest country to have Portuguese as an official language and the only one in the Americas;[12][13] it is also one of the most multicultural and ethnically diverse nations, due to over a century of mass immigration from around the world;[14] as well as the most populous Roman Catholic-majority country.",
    culture: "The core culture of Brazil is derived from Portuguese culture, because of its strong colonial ties with the Portuguese Empire.[525] Among other influences, the Portuguese introduced the Portuguese language, Roman Catholicism and colonial architectural styles. The culture was, however, also strongly influenced by African, indigenous and non-Portuguese European cultures and traditions.",
     climate: "The climate of Brazil comprises a wide range of weather conditions across a large area and varied topography, but most of the country is tropical." )
Country.create(name: "Canada", description: " Canada is a country in the northern part of North America. Its ten provinces and three territories extend from the Atlantic to the Pacific and northward into the Arctic Ocean, covering 9.98 million square kilometres (3.85 million square miles), making it the world's second-largest country by total area. Its southern and western border with the United States, stretching 8,891 kilometres (5,525 mi), is the world's longest bi-national land border. Canada's capital is Ottawa, and its three largest metropolitan areas are Toronto, Montreal, and Vancouver.",
    culture: "Canada's culture draws influences from its broad range of constituent nationalities, and policies that promote a 'just society' are constitutionally protected. Canada has placed emphasis on equality and inclusiveness for all its people. Multiculturalism is often cited as one of Canada's significant accomplishments, and a key distinguishing element of Canadian identity.",
     climate: "Average winter and summer high temperatures across Canada vary from region to region." )
Country.create(name: "El Salvador", description: "officially the Republic of El Salvador, El Salvador's capital and largest city is San Salvador. As of 2018, the country had a population of approximately 6.42 million, making it the smallest and second-least populated country in Central America.",
    culture: "Pulling from indigenous, colonial Spanish and African influences, a composite population was formed as a result of intermarrying between the natives, European settlers, and enslaved Africans. The Catholic Church plays an important role in the Salvadoran culture. ",
     climate: "El Salvador has a tropical climate with pronounced wet and dry seasons. Temperatures vary primarily with elevation and show little seasonal change." )

